name: Tensorflow2_GPU
channels:
  - defaults
dependencies:
  - alabaster=0.7.12
  - arrow=1.2.2
  - astroid=2.11.7
  - atomicwrites=1.4.0
  - attrs=21.4.0
  - autopep8=1.6.0
  - babel=2.9.1
  - backcall=0.2.0
  - bcrypt=3.2.0
  - beautifulsoup4=4.11.1
  - binaryornot=0.4.4
  - black=22.6.0
  - bleach=4.1.0
  - brotlipy=0.7.0
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - cffi=1.15.1
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.0.0
  - colorama=0.4.5
  - cookiecutter=1.7.3
  - cryptography=37.0.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - dill=0.3.4
  - docutils=0.18.1
  - entrypoints=0.4
  - flake8=4.0.1
  - glib=2.69.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icu=58.2
  - idna=3.3
  - imagesize=1.4.1
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - inflection=0.5.1
  - intervaltree=3.1.0
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - isort=5.9.3
  - jedi=0.18.1
  - jellyfish=0.9.0
  - jinja2=3.0.3
  - jinja2-time=0.2.0
  - jpeg=9e
  - jsonschema=4.4.0
  - jupyterlab_pygments=0.1.2
  - keyring=23.4.0
  - lazy-object-proxy=1.6.0
  - libffi=3.4.2
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.37
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mypy_extensions=0.4.3
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - nest-asyncio=1.5.5
  - numpydoc=1.4.0
  - openssl=1.1.1q
  - packaging=21.3
  - pandocfilters=1.5.0
  - paramiko=2.8.1
  - parso=0.8.3
  - pathspec=0.9.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pluggy=1.0.0
  - ply=3.11
  - poyo=0.5.0
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pycodestyle=2.8.0
  - pycparser=2.21
  - pydocstyle=6.1.1
  - pyflakes=2.4.0
  - pygments=2.11.2
  - pylint=2.14.5
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - python-lsp-black=1.0.0
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.3.3
  - python-slugify=5.0.2
  - pytz=2022.1
  - pywin32=302
  - pywin32-ctypes=0.2.0
  - pyyaml=6.0
  - qdarkstyle=3.0.2
  - qstylizer=0.1.10
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.0.3
  - qtconsole=5.2.2
  - qtpy=2.0.1
  - qtwebkit=5.212
  - requests=2.28.1
  - rope=0.22.0
  - rtree=0.9.7
  - setuptools=61.2.0
  - sip=6.6.2
  - six=1.16.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.1
  - sphinx=5.0.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - spyder=5.2.2
  - spyder-kernels=2.2.1
  - sqlite=3.39.2
  - testpath=0.6.0
  - text-unidecode=1.3
  - textdistance=4.2.1
  - three-merge=0.1.1
  - tinycss=0.4
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.1
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022a
  - ujson=5.4.0
  - unidecode=1.2.0
  - urllib3=1.26.11
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - wrapt=1.14.1
  - yaml=0.2.5
  - yapf=0.31.0
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - absl-py==1.2.0
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - array-record==0.4.1
    - astunparse==1.6.3
    - cachetools==5.2.0
    - cftime==1.6.2
    - comm==0.1.3
    - commonmark==0.9.1
    - cycler==0.11.0
    - cython==0.29.32
    - debugpy==1.6.7
    - dm-tree==0.1.7
    - emcee==3.1.2
    - etils==1.4.1
    - flatbuffers==23.5.26
    - fonttools==4.36.0
    - gast==0.4.0
    - google-auth==2.23.3
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - googleapis-common-protos==1.60.0
    - gpy==1.10.0
    - grpcio==1.59.0
    - gstools==1.4.0
    - h5netcdf==1.1.0
    - h5py==3.7.0
    - hankel==1.2.1
    - imageio==2.34.0
    - importlib-resources==6.0.1
    - ipykernel==6.22.0
    - ipywidgets==8.0.6
    - jax==0.3.24
    - jsonform==0.0.2
    - jsonsir==0.0.2
    - jupyter==1.0.0
    - jupyter-client==7.4.9
    - jupyter-console==6.6.3
    - jupyter-core==5.3.0
    - jupyter-events==0.6.3
    - jupyter-server==2.5.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-widgets==3.0.7
    - keras==2.14.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - libclang==14.0.6
    - markdown==3.4.1
    - matplotlib==3.5.3
    - meshio==5.3.4
    - ml-dtypes==0.2.0
    - mpmath==1.2.1
    - nbclassic==0.5.6
    - netcdf4==1.6.3
    - notebook==6.5.4
    - notebook-shim==0.2.3
    - numpy==1.26.1
    - oauthlib==3.2.0
    - opt-einsum==3.3.0
    - palettable==3.3.0
    - pandas==1.4.3
    - paramz==0.9.5
    - pillow==9.2.0
    - pip==23.3.1
    - platformdirs==3.5.0
    - prometheus-client==0.16.0
    - promise==2.3
    - prompt-toolkit==3.0.38
    - protobuf==4.24.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydoe==0.3.8
    - pyevtk==1.5.0
    - python-easyconfig==0.1.7
    - python-json-logger==2.0.7
    - pywinpty==2.0.10
    - pyzmq==25.0.2
    - requests-oauthlib==1.3.1
    - resource==0.2.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==12.5.1
    - rsa==4.9
    - scipy==1.9.0
    - seaborn==0.11.2
    - send2trash==1.8.2
    - sniffio==1.3.0
    - tensorboard==2.14.1
    - tensorboard-data-server==0.7.2
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.14.0
    - tensorflow-datasets==4.9.3
    - tensorflow-estimator==2.14.0
    - tensorflow-gpu==2.9.0
    - tensorflow-intel==2.14.0
    - tensorflow-io-gcs-filesystem==0.26.0
    - tensorflow-metadata==1.14.0
    - tensorflow-probability==0.22.1
    - termcolor==1.1.0
    - terminado==0.17.1
    - torch==1.13.1+cu116
    - torchaudio==0.13.1+cu116
    - torchvision==0.14.1+cu116
    - tornado==6.3.1
    - tqdm==4.65.0
    - traitlets==5.9.0
    - websocket-client==1.5.1
    - werkzeug==2.2.2
    - widgetsnbextension==4.0.7
    - xarray==2023.4.2
